name: ChatterBox
version: 0.3.1
main: com.jobud9.Chatterbox.Main
commands:
   cb:
      description:
      usage: |
   register:
      description:
      usage: |
permissions:
    cbox.canmute:
        description: Allows you to mute a player
        default: op