name: ChatterBox
version: 0.3.1
main: me.JnH.ChatterBox.Main
commands:
   cb:
      description:
      usage: |
permissions:
    cbox.canmute:
        description: Allows you to mute a player
        default: op